OPENEUROPA-2651: Fix bug with getRelatedEntities().
openeuropa/entity_meta_relation pull request #17
Opened 2020-01-23 16:02 UTC by hernani

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2020-01-24 10:36 UTC, upchuk requested changes

2020-01-24 10:36 UTC, upchuk commented on src/EntityMetaStorage.php
>      $relation_field = $entity instanceof EntityMetaInterface ? $entity_meta_relation_content_field : $entity_meta_relation_meta_field;
The `$relation_field` seems to be overridden here and not used anymore...

2020-01-28 14:40 UTC, upchuk approved these changes

2020-01-28 14:42 UTC, 22Alexandra approved these changes

2020-01-28 14:44 UTC, merged