OPENEUROPA-1972: Main logic and UI for entity meta relation.
openeuropa/entity_meta_relation pull request #4
Opened 2019-06-24 08:29 UTC by hernani

## OPENEUROPA-1972

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2019-07-15 09:38 UTC, brummbar requested changes

2019-07-15 09:38 UTC, brummbar commented on modules/emr_node/emr_node.module
> +  $form['#entity_builders'][] = [ContentEntityFormManager::class, 'entityBuilder'];
Can we put both entity builders and actions inside the service alter callback itself?

2019-07-15 09:38 UTC, brummbar commented on src/ContentEntityFormManager.php
> +class ContentEntityFormManager {
Let's add interfaces to all the services.

2019-07-15 09:38 UTC, brummbar commented on src/Entity/EntityMeta.php
> +      if (!empty($field)) {
```suggestion
      if (!$this->get($field)->isEmpty()) {
```

2019-07-15 09:38 UTC, brummbar commented on src/Annotation/EntityMetaRelation.php
> + * Defines entity_meta_relation annotation object.
```suggestion
 * Defines an entity meta relation annotation object.
```

2019-07-15 09:38 UTC, brummbar commented on src/ContentEntityFormManager.php
> +   *   The EntityMetaRelationManager.
```suggestion
   *   The entity meta relation manager service.
```

2019-07-15 09:38 UTC, brummbar commented on src/ContentEntityFormManager.php
> +  public function __construct(EntityMetaRelationManager $entity_meta_relation_manager, EntityMetaRelationPluginManager $pluginManager) {
Let's use only snake case.

2019-07-15 09:38 UTC, brummbar commented on src/ContentEntityFormManager.php
> +   *   Form elements to be added.
```suggestion
   *   The form array.
```

2019-07-15 09:38 UTC, brummbar commented on src/EntityMetaRelationContentFormPluginBase.php
> +    $emrFormKeys = $form['emr_form_keys']['#value'] ?? [];
This logic shouldn't be in here I think, it should be handled more in the invoking method. But then we would need to also invoke the `isApplicable()` in there.
The thing is that if a plugin overrides this method, it would need to re-do the logic to keep track of the plugin.

2019-07-15 09:38 UTC, brummbar commented on src/EntityMetaRelationContentFormPluginBase.php
> +    $emrFormKeys = $form['emr_form_keys']['#value'] ?? [];
Also we could try to use the form state storage to save this data, instead of the form itself.

2019-07-15 09:38 UTC, brummbar commented on src/EntityMetaRelationContentFormPluginBase.php
> +      '#attributes' => ['id' => 'edit-meta-reference'],
This should be unique.

2019-07-15 09:38 UTC, brummbar commented on src/EntityMetaRelationPluginBase.php
> +      if ($field_definition->getType() == 'entity_reference_revisions' && $field_definition->getSetting('target_type') == 'node') {
```suggestion
      if ($field_definition->getType() == 'entity_reference_revisions' && $field_definition->getSetting('target_type') === $content_entity->getEntityTypeId()) {
```

2019-07-15 09:38 UTC, brummbar commented on src/EntityMetaRelationPluginManager.php
> + * EntityMetaRelation plugin manager.
🍝

2019-07-15 09:38 UTC, brummbar commented on src/Exception/EntityMetaEmpty.php
> +class EntityMetaEmpty extends \Exception {
```suggestion
class EntityMetaEmptyException extends \Exception {
```

2019-07-15 09:38 UTC, brummbar commented on src/Exception/EntityMetaEmpty.php
> +class EntityMetaEmpty extends \Exception {
```suggestion
class EmptyEntityMetaException extends \Exception {
```

2019-07-15 09:38 UTC, brummbar commented on tests/kernel/EntityMetaRelationTest.php
> +    $this->assertNotEqual($related_entity_meta, []);
```suggestion
    $this->assertNotEmpty($related_entity_meta);
```

2019-07-15 09:38 UTC, brummbar commented on src/EntityMetaRelationContentFormPluginBase.php
> +      '#default_value' => $entity_meta_relations[$entityMetaBundle][0] ?? NULL,
I created a node and didn't set anything in the visual field. Created yet another revision without visual value. Then I edited the node again, unchecked the "create new revision", set red in the visual, and saved. When I edit, 3 entity metas are loaded, and the first one is shown, with an empty value in the visual field, while it should be red.

2019-07-15 09:38 UTC, brummbar commented on src/Entity/EntityMeta.php
> +      if (!empty($field)) {
By testing, this is not enough to check if an entity is empty, as values like language are populated so it still saves it.

2019-07-15 09:38 UTC, brummbar commented on src/Entity/EntityMeta.php
> +    $field_blacklist = $this->traitGetFieldsToSkipFromTranslationChangesCheck($this);
Nit: we can use lowerCamelCase or snake_case for variable names but they shouldn't be mixed in the same file.

2019-07-15 09:47 UTC, brummbar commented on modules/emr_node/emr_node.module
> +  if (!$entity->isNew() && (!isset($entity->emr_no_copy) || !$entity->emr_no_copy)) {
Shouldn't we copy the relations only if a new revision has been created?

2019-07-18 13:29 UTC, brummbar submitted a review, later dismissed

2019-08-05 09:30 UTC, upchuk requested changes

2019-08-05 09:30 UTC, upchuk commented on src/Plugin/EntityMetaRelationContentFormPluginBase.php
> +  public function buildFormContainer(array &$form, FormStateInterface $form_state, string $key) {
Does this need to be public?

2019-08-05 09:30 UTC, upchuk commented on src/Plugin/EntityMetaRelationContentFormPluginBase.php
>   * Base class for plugins that need to be directly embedded in content forms.
`Base class for plugins that need to be embedded in content forms.`

2019-08-08 07:42 UTC, upchuk submitted a review, later dismissed

2019-08-08 12:32 UTC, brummbar approved these changes

2019-08-08 12:38 UTC, upchuk approved these changes

2019-08-08 12:39 UTC, merged