EWPP-965: Using a counter for the emr default revision.
openeuropa/entity_meta_relation pull request #53
Opened 2021-04-13 10:36 UTC by upchuk

2021-04-14 14:58 UTC, brummbar requested changes

2021-04-14 14:58 UTC, brummbar commented on emr.install
> +        'not null' => TRUE,
We can put unsigned here too.

2021-04-14 14:58 UTC, brummbar commented on emr.post_update.php
> +function emr_post_update_00003(&$sandbox) {
We can consider this as "fixing the API" and move it to a hook_update_N() implementation so that we can drop the field on one go.

2021-04-14 14:58 UTC, brummbar commented on src/Entity/EntityMeta.php
> +    // default. See EntityMetaStorage::doPostSave().
This field should be dropped and we make either a computed field or use a simple not stored property on the entity to mark default revisions.

2021-04-14 14:58 UTC, brummbar commented on src/Entity/Query/Sql/Query.php
>        $this->condition('emr_default_revision', TRUE);
Isn't this line not needed anymore?

2021-04-14 14:58 UTC, brummbar commented on src/Entity/Query/Sql/Query.php
> +      $this->sqlQuery->join('entity_meta_default_revision', 'default_revision_table', "base_table.revision_id = default_revision_table.default_revision_id");
Wonder if we should do something like below where we use `revisionKey` instead of directly putting `revision_id` ?

2021-04-14 14:58 UTC, brummbar commented on src/EntityMetaStorage.php
>        }
This costs an extra query to check the value and one to update it, maybe we can just update it without re-checking?

2021-04-14 14:58 UTC, brummbar commented on src/EntityMetaStorage.php
> +  protected function getDefaultRevisionId(int $id): ?string {
This should return int.

2021-04-20 22:06 UTC, brummbar requested changes

2021-04-20 22:06 UTC, brummbar commented on emr.install
> +  \Drupal::database()->schema()->createTable('entity_meta_default_revision', $schema);
We need to move the table creation to a separate hook_update_N() as under this we are creating batches and this fails when more than one batch exists.

2021-04-21 11:38 UTC, brummbar commented on src/EntityMetaStorage.php
>        }
Write queries are more expensive than reads, so my comment is wrong.

2021-04-21 11:38 UTC, brummbar submitted a review, later dismissed

2021-04-22 16:05 UTC, hernani approved these changes, later dismissed

2021-04-26 08:31 UTC, hernani approved these changes, later dismissed

2021-04-26 08:34 UTC, hernani approved these changes

2021-04-26 09:32 UTC, brummbar approved these changes

2021-04-26 09:34 UTC, merged