EWPP-1494: Improve performance for getRelatedEntities().
openeuropa/entity_meta_relation pull request #57
Opened 2021-09-09 13:36 UTC by hernani

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-09-10 12:00 UTC, brummbar requested changes
Looks good, performance improvement is substantial.

2021-09-10 12:00 UTC, brummbar commented on src/EntityMetaStorage.php
> +          $related_entities[$id] = $related_entity;
```suggestion
          if ($related_entity instanceof ContentEntityInterface) {
            $related_entities[$id] = $related_entity;
            break;
          }
```

2021-09-13 07:33 UTC, upchuk approved these changes

2021-09-13 08:26 UTC, brummbar approved these changes

2021-09-13 08:39 UTC, merged