EWPP-1914: Update to PHP8
openeuropa/entity_meta_relation pull request #59
Opened 2022-02-01 15:30 UTC by yenyasinn

2022-02-03 16:37 UTC, 22Alexandra requested changes
Need to create src folder under tests/

2022-02-07 08:03 UTC, 22Alexandra requested changes, later dismissed

2022-02-07 08:03 UTC, 22Alexandra commented on composer.json
> +        "Explicit requirement amphp/parallel-functions due to grumphp errors. Remove when openeuropa/code-review will be updated",
It has been soft locked in code-review 2.0.0-alpha3, so we can remove it from here.

2022-02-07 12:33 UTC, nagyad approved these changes, later dismissed

2022-02-08 09:44 UTC, hernani approved these changes

2022-02-08 09:45 UTC, nagyad approved these changes

2022-02-08 09:48 UTC, merged